// CardService.cs
// Service for SmartPGP card management operations on Windows

using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

namespace SmartPGP.OutlookHelper;

/// <summary>
/// Service for SmartPGP card management operations
/// </summary>
public class CardService
{
    private readonly ILogger<CardService> _logger;

    public CardService(ILogger<CardService> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Execute a GPG command and return the output
    /// </summary>
    private async Task<(string output, string error, int exitCode)> ExecuteGPG(string command, string? input = null, int timeoutSeconds = 30)
    {
        var processInfo = new ProcessStartInfo
        {
            FileName = "cmd.exe",
            Arguments = $"/c {command}",
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var process = new Process { StartInfo = processInfo };
        var outputBuilder = new StringBuilder();
        var errorBuilder = new StringBuilder();

        process.OutputDataReceived += (sender, e) => { if (e.Data != null) outputBuilder.AppendLine(e.Data); };
        process.ErrorDataReceived += (sender, e) => { if (e.Data != null) errorBuilder.AppendLine(e.Data); };

        process.Start();
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();

        // Write input if provided
        if (!string.IsNullOrEmpty(input))
        {
            await process.StandardInput.WriteAsync(input);
            process.StandardInput.Close();
        }

        // Wait for completion with timeout
        var completed = await Task.Run(() => process.WaitForExit(timeoutSeconds * 1000));

        if (!completed)
        {
            process.Kill();
            throw new TimeoutException($"Command timed out after {timeoutSeconds} seconds");
        }

        return (outputBuilder.ToString(), errorBuilder.ToString(), process.ExitCode);
    }

    /// <summary>
    /// Generate a new RSA keypair on the card
    /// </summary>
    public async Task<GenerateKeypairResponse> GenerateKeypair(int keySize = 2048, string adminPin = "12345678")
    {
        try
        {
            _logger.LogInformation("Generating {KeySize}-bit keypair on card", keySize);

            // Verify card is present
            var (cardOutput, _, cardExitCode) = await ExecuteGPG("gpg --card-status");
            if (cardExitCode != 0)
            {
                throw new CardException("SmartPGP card not detected");
            }

            // Check if card has SmartPGP/OpenPGP applet
            if (!cardOutput.Contains("Application ID") && !cardOutput.Contains("Reader"))
            {
                throw new CardException("No valid OpenPGP card found");
            }

            // Generate keypair using GPG
            var gpgCommands = $@"admin
generate
n
{adminPin}
{adminPin}
0
SmartPGP User
smartpgp@example.com
Generated by SmartPGP Helper
o
quit
";

            var (output, error, exitCode) = await ExecuteGPG(
                "gpg --command-fd 0 --status-fd 2 --card-edit",
                gpgCommands,
                120); // 2 minute timeout for key generation

            if (exitCode != 0 && !output.Contains("KEY_CREATED") && !error.Contains("KEY_CREATED"))
            {
                throw new CardException($"Key generation failed: {error}");
            }

            // Extract key ID from output
            var keyId = ExtractKeyId(output + error);

            return new GenerateKeypairResponse
            {
                Success = true,
                Message = $"RSA-{keySize} keypair generated successfully on card",
                KeyId = keyId
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating keypair");
            throw;
        }
    }

    /// <summary>
    /// Change the user PIN on the card
    /// </summary>
    public async Task<ChangePinResponse> ChangePin(string currentPin, string newPin)
    {
        try
        {
            _logger.LogInformation("Changing PIN on card");

            // Validate PIN lengths
            if (newPin.Length < 6 || newPin.Length > 127)
            {
                throw new CardException("PIN must be between 6 and 127 characters");
            }

            // Use GPG passwd command to change PIN
            var gpgCommands = $@"admin
passwd
1
{currentPin}
{newPin}
{newPin}
quit
";

            var (output, error, exitCode) = await ExecuteGPG(
                "gpg --command-fd 0 --status-fd 2 --card-edit",
                gpgCommands,
                30);

            // Check for success indicators
            var combined = output + error;
            if (combined.Contains("PIN changed", StringComparison.OrdinalIgnoreCase) ||
                combined.Contains("succeeded", StringComparison.OrdinalIgnoreCase) ||
                exitCode == 0)
            {
                // Kill GPG agent to release card
                await ExecuteGPG("gpgconf --kill gpg-agent");
                await Task.Delay(500);

                return new ChangePinResponse
                {
                    Success = true,
                    Message = "PIN changed successfully"
                };
            }

            // Check for specific error cases
            if (combined.Contains("Bad PIN", StringComparison.OrdinalIgnoreCase) ||
                combined.Contains("incorrect", StringComparison.OrdinalIgnoreCase))
            {
                throw new CardException("Current PIN is incorrect");
            }

            throw new CardException($"PIN change failed: {error}");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error changing PIN");
            throw;
        }
    }

    /// <summary>
    /// Delete all keys from the card (factory reset)
    /// </summary>
    public async Task<DeleteKeypairResponse> DeleteKeypair(string adminPin = "12345678")
    {
        try
        {
            _logger.LogInformation("Performing factory reset on card");

            // Use GPG factory-reset command
            var gpgCommands = @"admin
factory-reset
yes
yes
quit
";

            var (output, error, exitCode) = await ExecuteGPG(
                "gpg --command-fd 0 --status-fd 2 --card-edit",
                gpgCommands,
                30);

            // Kill GPG agent to release card
            await ExecuteGPG("gpgconf --kill gpg-agent");
            await ExecuteGPG("gpgconf --kill scdaemon");
            await Task.Delay(1000);

            var combined = output + error;
            if (combined.Contains("reset", StringComparison.OrdinalIgnoreCase) ||
                combined.Contains("factory", StringComparison.OrdinalIgnoreCase) ||
                exitCode == 0)
            {
                return new DeleteKeypairResponse
                {
                    Success = true,
                    Message = "Card reset to factory defaults. Default PIN: 123456, Admin PIN: 12345678"
                };
            }

            throw new CardException($"Factory reset failed: {error}");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error deleting keypair");
            throw;
        }
    }

    /// <summary>
    /// Get card status information
    /// </summary>
    public async Task<CardStatusResponse> GetCardStatus()
    {
        try
        {
            var (output, error, exitCode) = await ExecuteGPG("gpg --card-status");

            if (exitCode != 0)
            {
                throw new CardException($"Cannot read card status: {error}");
            }

            // Parse card status
            var hasSignKey = output.Contains("Signature key", StringComparison.OrdinalIgnoreCase);
            var hasEncKey = output.Contains("Encryption key", StringComparison.OrdinalIgnoreCase) ||
                            output.Contains("General key", StringComparison.OrdinalIgnoreCase);
            var hasAuthKey = output.Contains("Authentication key", StringComparison.OrdinalIgnoreCase);

            // Extract serial number
            string? serialNumber = null;
            var serialMatch = Regex.Match(output, @"Serial number.*?([0-9A-F]+)", RegexOptions.IgnoreCase);
            if (serialMatch.Success)
            {
                serialNumber = serialMatch.Groups[1].Value;
            }

            return new CardStatusResponse
            {
                CardPresent = true,
                HasSigningKey = hasSignKey,
                HasEncryptionKey = hasEncKey,
                HasAuthenticationKey = hasAuthKey,
                SerialNumber = serialNumber,
                RawStatus = output
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting card status");
            throw;
        }
    }

    /// <summary>
    /// Helper to extract key ID from GPG output
    /// </summary>
    private string? ExtractKeyId(string output)
    {
        var patterns = new[]
        {
            @"key ([0-9A-F]{8,16})",
            @"KEY_CREATED [SP] ([0-9A-F]{40})",
            @"fingerprint:\s*([0-9A-F\s]+)"
        };

        foreach (var pattern in patterns)
        {
            var match = Regex.Match(output, pattern, RegexOptions.IgnoreCase);
            if (match.Success)
            {
                return match.Groups[1].Value.Replace(" ", "");
            }
        }

        return null;
    }
}

// MARK: - Response Models

public record GenerateKeypairResponse
{
    public bool Success { get; init; }
    public string Message { get; init; } = string.Empty;
    public string? KeyId { get; init; }
}

public record ChangePinResponse
{
    public bool Success { get; init; }
    public string Message { get; init; } = string.Empty;
}

public record DeleteKeypairResponse
{
    public bool Success { get; init; }
    public string Message { get; init; } = string.Empty;
}

public record CardStatusResponse
{
    public bool CardPresent { get; init; }
    public bool HasSigningKey { get; init; }
    public bool HasEncryptionKey { get; init; }
    public bool HasAuthenticationKey { get; init; }
    public string? SerialNumber { get; init; }
    public string RawStatus { get; init; } = string.Empty;
}

// MARK: - Exception

public class CardException : Exception
{
    public CardException(string message) : base(message) { }
    public CardException(string message, Exception innerException) : base(message, innerException) { }
}
